### ISSUE TITLE
Model id is generic

### ISSUE THREAD

**Issue by holmey** [typesense/showcase-conversational-search-pg-essays#2]
I have not been able to set the model ID myself like you did here

https://github.com/typesense/showcase-conversational-search-pg-essays/blob/b7c8dac7c844380d0fb748411d778ad0262543b1/dataset/indexInTypesense.ts#L125

Therefore i had to query the ID like this

```bash
curl 'https://...:8108/conversations/models' \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "X-TYPESENSE-API-KEY: ..."
```

 and use this ID here

https://github.com/typesense/showcase-conversational-search-pg-essays/blob/b7c8dac7c844380d0fb748411d778ad0262543b1/src/lib/actions.ts#L48

Have i been missing something or could this be part of the documentation? If so i could send you a merge request for that.

**Comment by jasonbosco** [comment]
We only added this feature publicly in a recent RC build. Could you try this with 27.1 of Typesense Server and reopen the issue if you still see any issues?
