### ISSUE TITLE
Link past conversations to model

### ISSUE THREAD

**Issue by holmey** [typesense/showcase-conversational-search-pg-essays#3]
The documentation says you can query past conversations like this

https://typesense.org/docs/26.0/api/conversational-search-rag.html#managing-past-conversations
```bash
curl 'http://localhost:8108/conversations' \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}"
```
I think your approach of linking the conversations to specific models seems to me to be a more sustainable approach but it is not working for me and I also could not find any documentation thats describing this line of code.

https://github.com/typesense/showcase-conversational-search-pg-essays/blob/b7c8dac7c844380d0fb748411d778ad0262543b1/dataset/indexInTypesense.ts#L141

Are you maybe using a version other than the latest publicly available version?

**Comment by jasonbosco** [comment]
This was a breaking change we had to do in v27.1 of Typesense Server. 

You want to follow the latest docs here: https://typesense.org/docs/27.1/api/conversational-search-rag.html
